path   = require 'path'
ake    = require 'cc.ake'

# add node_modules binaries to head of path
do ake.nodeModulePath

task 'web', 'build cc/loader.js for use in websites', (options) ->
  ake.assert 'mkdir -p cc',
  'coffee -p lib/cc/webloader.coffee > cc/loader.js'

task 'clean', 'clean everything generated by build system', (options) ->
  ake.assert "rm -rf `grep '^/' .gitignore | sed 's,^/,,'`"

task 'test', 'test cc.loader', (options) ->
  # joose-2.1: wget http://joose-js.googlecode.com/files/joose.mini.js -O $@
  ake.assert ake.invoke('web'),
    'ln -sf ../cc test'
    'cp -n node_modules/joose/joose-all-web.js test/joose.js'
    './bin/ccbaker test/lib/root.js test/lib/joose/root.js > test/lib/packed.js'
    'coffee -c test/lib/incmissing.coffee'
    ->
      express = require 'express'
      app     = express.createServer()
      port = process.env.port or 8012
      app.configure () ->
        app.use express.static path.join(process.cwd(), 'test')
      console.log "cc.loader test server listening on: #{port}"
      console.log "please go to http://localhost:#{port}/"
      app.listen port

# vim:ts=2 sw=2
